### ISSUE TITLE
grunt-contrib-watch breaks grunt-notify's hooks

### ISSUE THREAD

**Issue by dylang** [dylang/grunt-notify#46]
[grunt-contrib-watch](https://github.com/gruntjs/grunt-contrib-watch) is replacing the `grunt.warn`, `grunt.fail.warn`, etc functions that `grunt-notify` hooks into for showing notifications. 

See: https://github.com/gruntjs/grunt-contrib-watch/issues/232

I may create a workaround where I hook into `grunt.log.writeln` and use  the messages that `grunt-contrib-watch` is printing as the notify message.

**Comment by sercaneraslan** [comment]
+1
