### ISSUE TITLE
Remote Notifications

### ISSUE THREAD

**Issue by jlopinto** [dylang/grunt-notify#63]
It's more a question than a issue, but i wonder if it's possible to send notifications remotely.

I code on Windows & OSX, but my files are stored/edited on a remote ubuntu server through a shared folder with samba . I launch "grunt watch" through ssh. And indeed i hear a simple "bip" sent by the terminal when something went wrong

Is there a way to send notification for example from ubuntu to Windows in this setup ?

Regards

**Comment by Chi-teck** [comment]
[Here](https://github.com/Chi-teck/notify-send-http-server) is my workaround. It works in conjunction with _curl_ and _grunt exec_.

**Comment by alpha01** [comment]
Shameless plug, I'm the maintainer of [vagrant-notify](https://github.com/fgrehm/vagrant-notify).
My companies' dev team uses this vagrant plugin to get grunt-notify notifications from inside a Vagrant VM.
